name: Java CI

on:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive artifacts (Build)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Build
          path: ./bin/*
